### ISSUE TITLE
PublishOptions broken, exclude_me not acknowledged

### ISSUE THREAD

**Issue by deceze** [crossbario/autobahn-python#618]
Tests running on Python 3.5.1, autobahn 0.13.0, crossbar 0.13.0, using asyncio version.

Simple test case:

```python
class Test(ApplicationSession):
    async def onJoin(self, details):
        logging.info(await self.subscribe(self.foo, 'foo', SubscribeOptions(details_arg='details')))
        logging.info('Subscribed, sending test...')
        logging.info(await self.publish('foo', 42, options=PublishOptions(acknowledge=True, exclude_me=False)))
        logging.info('Test sent.')

    def foo(self, bar: int, details: EventDetails):
        logging.info('foo %s', details)
        self.disconnect()
        asyncio.get_event_loop().stop()

ApplicationRunner('ws://localhost:8080', 'test').run(Test)
```

The event is never triggered, the output is merely:

```
2016-03-29T12:28:02 Subscription(id=4306902726829498, is_active=True)
2016-03-29T12:28:02 Registered, sending test...
2016-03-29T12:28:02 Publication(id=358474513636002, was_encrypted=False)
2016-03-29T12:28:02 Test sent.
```

I was encountering this while playing around with custom serialisers, and looking at the actual serialised message, it's merely:

    [16, 2, {'acknowledge': True}, 'foo', (42,)]

The `exclude_me=False` option is getting lost somewhere. When setting `exclude_me=True` it *does* show up in the serialised message!

Somewhat unrelated but also concerning, when setting `eligible_authrole=['foo']`, the Crossbar router(!) has this in its log:

```
2016-03-29T12:29:08+0200 [Router       2277] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "/usr/local/lib/python3.5/site-packages/autobahn/wamp/serializer.py", line 131, in unserialize
    msg = Klass.parse(raw_msg)
  File "/usr/local/lib/python3.5/site-packages/autobahn/wamp/message.py", line 1377, in parse
    for _authrole in option_exclude_authrole:
UnboundLocalError: local variable 'option_exclude_authrole' referenced before assignment
```

**Comment by meejah** [comment]
I think the main issue here should have been fixed on Autobahn's master by this PR: https://github.com/crossbario/autobahn-python/pull/615

Can you try with (autobahn's) master?

The unbound local looks like a bug, too...but probably in Autobahn?

**Comment by deceze** [comment]
I can confirm that #615 seems to have fixed this already. :+1:
`eligible_authrole`/`UnboundLocalError` still persists though.

**Comment by oberstet** [comment]
fixed on HEAD
